tasks:
  - name: Install dependencies & run dev environment
    init: npm install
    command: npm run dev
    openMode: split-left
  - name: A terminal for git
    command: echo "here's an open terminal for git"
    openMode: split-right

ports:
  - port: 3000
    onOpen: open-preview
    visibility: private
    
vscode:
  extensions:
    - esbenp.prettier-vscode@6.3.2
